### ISSUE TITLE
Doesn't work on servers that open another window

### ISSUE THREAD

**Issue by checkraisefold** [Lyut/BYONDHook#1]
for obvious reasons, servers that create another dreamseeker instance and reconnect will not work with this

**Comment by Lyut** [comment]
for which obvious reasons?

it works fine for me on such servers, how are you doing this?

**Comment by Lyut** [comment]
just add an import to the IAT of dreamseeker.exe from Main in your compiled hook dll, code will automatically execute on launch

![This is an image](https://i.imgur.com/Gmd3TKM.png)

**Comment by Lyut** [comment]
Confirmed working, no response in almost 2 weeks, assuming the issue is fixed.
Feel free to comment for further questions

https://user-images.githubusercontent.com/462853/145218579-a6dd4f60-8875-4b7e-8584-e78228314f6f.mp4

**Comment by Lyut** [comment]
commit a26937cb788713dde8dc7760c4eb07794dd8a172 fixes this "issue", you can use DSPatcher.exe to patch dreamseeker.exe and make it automatically run BYONDHook on every startup @checkraisefold

**Comment by checkraisefold** [comment]
@Lyut spoiler: if you plain add a DLL to the IAT of dreamseeker.exe or byondcore.dll, you will trigger the intentional anticheat that just crashes the game when it detects a non-trusted import

on most computers at least...

**Comment by Lyut** [comment]
@checkraisefold As long as the DLL is outside BYOND's directory (reason why I instruct placing the DLL in a custom folder e.g. C:\BYOND) and the import is added from an absolute path (e.g. C:\Windows\system32\kernel32.dll insteaad of kernel32.dll) the anticheat fails.

Thanks for the heads up, really appreciated. If you have more info about that I'd be happy to hear from you.

**Comment by checkraisefold** [comment]
not gonna lie, that's really dumb that you can just do that. i managed to just hook the anticheat and turn it off, but spent a while figuring out where it was

**Comment by Lyut** [comment]
that's interesting, I personally haven't took any look at the anticheat because I straight up assumed there was some sort of check when it would crash with any import from any DLL. I randomly tried the solution above and came up to the conclusion it works, so I never bothered again.

great to hear i'm not the only one working on BYOND cheats. I'm always open for suggestions or PRs!
